routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Backend\WelcomeController@index')->name('root');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/films','Backend\FilmController@index')->name('film.index');
Route::get('/films/{slug}','Backend\FilmController@details')->name('film.details');

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' => ['role:administrator']], function () {

	Route::get('/dashboard','Backend\AdminDashboardController@adminDashboard')->name('dashboard');

	/*.............................START - User Management - START............................*/
	Route::group(['prefix' => 'users','as' => 'users.'], function () {
		Route::get('/list','Backend\UserManagementController@index')->name('index');
		Route::get('/create','Backend\UserManagementController@create')->name('create');
		Route::post('/store','Backend\UserManagementController@store')->name('store');
		Route::get('/edit/{id}','Backend\UserManagementController@edit')->name('edit');
		Route::post('/update/{id}','Backend\UserManagementController@update')->name('update');
		Route::get('/delete/{id}','Backend\UserManagementController@delete')->name('delete');
		Route::get('/ban/{id}','Backend\UserManagementController@ban')->name('ban');
		Route::get('/datatable/users','Backend\UserManagementController@userData')->name('datatables');
	});
	/*...............................END - User Management - END..............................*/

	/*.............................START - Country Management - START............................*/
	Route::group(['prefix' => 'country','as' => 'country.'], function () {
		Route::get('/list','Backend\CountryController@index')->name('index');
		Route::get('/create','Backend\CountryController@create')->name('create');
		Route::post('/store','Backend\CountryController@store')->name('store');
		Route::get('/edit/{id}','Backend\CountryController@edit')->name('edit');
		Route::post('/update/{id}','Backend\CountryController@update')->name('update');
		Route::get('/delete/{id}','Backend\CountryController@delete')->name('delete');
		Route::get('/datatable/countries','Backend\CountryController@countryData')->name('datatables');
	});
	/*...............................END - Country Management - END..............................*/

	/*.............................START - Genre Management - START............................*/
	Route::group(['prefix' => 'genre','as' => 'genre.'], function () {
		Route::get('/list','Backend\GenreController@index')->name('index');
		Route::get('/create','Backend\GenreController@create')->name('create');
		Route::post('/store','Backend\GenreController@store')->name('store');
		Route::get('/edit/{id}','Backend\GenreController@edit')->name('edit');
		Route::post('/update/{id}','Backend\GenreController@update')->name('update');
		Route::get('/delete/{id}','Backend\GenreController@delete')->name('delete');
		Route::get('/datatable/genres','Backend\GenreController@genreData')->name('datatables');
	});
	/*...............................END - Genre Management - END..............................*/
});
Route::group(['middleware' => ['role:administrator']], function () {
	/*.............................START - Genre Management - START............................*/
	Route::group(['prefix' => 'film','as' => 'film.'], function () {
		Route::get('/create','Backend\FilmController@create')->name('create');
	});
	/*...............................END - Genre Management - END..............................*/
});

app/Http/Controllers/Backend/AdminDashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminDashboardController extends Controller
{
    public function adminDashboard()
    {
    	return view('backend.dashboard.dashboard');
    }

    public function register()
    {
    	return view('backend.auth.register');
    }

    
}

app/Http/Controllers/Backend/CountryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use Illuminate\Http\Request;
use App\Country;

class CountryController extends Controller
{
    public function index()
    {
        return view('backend.country.index');
    }

    public function create()
    {
    	return view('backend.country.create');
    }

    public function store(Request $request)
    {
        $country = new Country();
        $country->name = $request->name;
        $country->code = $request->code;
        $country->save();
        return redirect()->route('admin.country.index');
    }

    public function edit($id)
    {
        $country = Country::find($id);
        return view('backend.country.edit',compact('country'));
    }

    public function update(Request $request,$id)
    {
        $country = Country::find($id);
        $country->name = $request->name;
        $country->code = $request->code;
        $country->update();
        return redirect()->route('admin.country.index');
    }

    public function delete($id)
    {  
        $country = Country::find($id);
        $country->delete();
        return redirect()->route('admin.country.index');
    }


    protected function countryData(Request $request)
    {
        $countries = Country::get();
        $datatables = Datatables::of($countries);

        return $datatables
            ->addColumn('action', function ($country) {
                return '<a href="edit/'.$country->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$country->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>';
            })
            ->editColumn('id',function($country){
                return '<b>'.$country->id.'.</b>';
            })
            ->editColumn('name',function($country){
                return $country->name;
            })
            ->rawColumns(['id','action'])
            ->make(true);
    }
}

app/Http/Controllers/Backend/FilmController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Country;
use App\Genre;
use App\Film;
use App\Comment;
use Auth;

class FilmController extends Controller
{
    public function index()
    {
        return view('frontend.film.index');
    }

    public function create()
    {
        $countries = Country::get();
        $genres = Genre::get();
        return view('frontend.film.create',compact('countries','genres'));
    }

    public function details($slug)
    {
        $film = Film::select('films.*','countries.name as country')
            ->where('films.slug',$slug)
            ->join('countries','countries.id','=','films.country_id')
            ->first();
        $genres = Genre::whereIn('id',json_decode($film->genre_id))->get();
        $film->getFirstMedia('FilmImage');
        if( count($film->media))
        $film->imgSrc = '/storage/' . $film->media[0]->id . '/' . $film->media[0]->file_name;
        $comments = Comment::where('film_id',$film->id)->get();
        if(Auth::check()) $isLoggedIn = 'true';
        else $isLoggedIn = 'false';
        return view('frontend.film.details',compact('film','comments','genres','isLoggedIn'));
    }
}

app/Http/Controllers/Backend/GenreController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use Illuminate\Http\Request;
use App\Genre;

class GenreController extends Controller
{
    public function index()
    {
        return view('backend.genre.index');
    }

    public function create()
    {
    	return view('backend.genre.create');
    }

    public function store(Request $request)
    {
        $genre = new Genre();
        $genre->name = $request->name;
        $genre->description = $request->description;
        $genre->save();
        return redirect()->route('admin.genre.index');
    }

    public function edit($id)
    {
        $genre = Genre::find($id);
        return view('backend.genre.edit',compact('genre'));
    }

    public function update(Request $request,$id)
    {
        $genre = Genre::find($id);
        $genre->name = $request->name;
        $genre->description = $request->description;
        $genre->update();
        return redirect()->route('admin.genre.index');
    }

    public function delete($id)
    {  
        $genre = Genre::find($id);
        $genre->delete();
        return redirect()->route('admin.genre.index');
    }


    protected function genreData(Request $request)
    {
        $genres = Genre::get();
        $datatables = Datatables::of($genres);

        return $datatables
            ->addColumn('action', function ($genre) {
                return '<a href="edit/'.$genre->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$genre->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>';
            })
            ->editColumn('id',function($genre){
                return '<b>'.$genre->id.'.</b>';
            })
            ->editColumn('name',function($genre){
                return $genre->name;
            })
            ->rawColumns(['id','action'])
            ->make(true);
    }
}

app/Http/Controllers/Backend/UserManagementController.php
<?php

namespace App\Http\Controllers\Backend;

use DB;
use Auth;
use App\User;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;

class UserManagementController extends Controller
{
	public function index()
    {
        return view('backend.user-management.index');
    }

    public function create()
    {
        $roles = Role::get();
    	return view('backend.user-management.create',compact('roles'));
    }

    public function store(StoreUserRequest $request)
    {
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();
        $user->assignRole($request->roles);
        return redirect()->route('admin.users.index');
    }

    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::get();
        $existingRoles = array();
        foreach ($user->roles as $role)   array_push($existingRoles, $role->name);
        return view('backend.user-management.edit',compact('user','roles','existingRoles'));
    }

    public function update(UpdateUserRequest $request,$id)
    {
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->update();
        $user->syncRoles($request->roles);
        return redirect()->route('admin.users.index');
    }

    public function delete($id)
    {  
        $user = User::find($id);
        $user->deleted_by = Auth::user()->id;
        $user->update();
        $user->delete();
        return redirect()->route('admin.users.index');
    }

    public function ban($id)
    {
        $user = User::find($id);
        $user->is_banned = !$user->is_banned;
        $user->update();
        return redirect()->route('admin.users.index');
    }

    protected function userData(Request $request)
    {
        $users = User::get();
        $datatables = Datatables::of($users);

        return $datatables
            ->addColumn('action', function ($user) {
                if($user->is_banned)
                    return '<a href="edit/'.$user->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$user->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>' . ' <a href="ban/'.$user->id.'" class="btn btn-xs btn-success" onclick="return confirm(\'Are you sure?\')"><i class="fa fa-ban"></i> Unban</a>';
                return '<a href="edit/'.$user->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$user->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>' . ' <a href="ban/'.$user->id.'" class="btn btn-xs btn-warning" onclick="return confirm(\'Are you sure?\')"><i class="fa fa-ban"></i> Ban</a>';
            })
            ->editColumn('id',function($user){
                return '<b>'.$user->id.'.</b>';
            })
            ->editColumn('name',function($user){
                return $user->name;
            })
            ->setRowClass(function ($user) {
                return $user->is_banned == 0 ? 'alert-success' : 'alert-danger';
            })
            ->editColumn('created_at', function ($user) {
                return $user->created_at->format('d-M-Y');
            })
            ->rawColumns(['id','action'])
            ->make(true);
    }
}

app/Http/Controllers/Backend/WelcomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {
        return view('welcome');
    }
}

resources/views/backend/includes/footer.blade.php
<footer class="sticky-footer bg-white">
	<div class="container my-auto">
	  <div class="copyright text-center my-auto">
	    <span>Copyright &copy; Chatleads PHP-Challenge Project <b id="year"></b></span>
	  </div>
	</div>
</footer>

<script type="text/javascript">
	function myFunction() {
	  var d = new Date();
	  var n = d.getFullYear();
	  document.getElementById("year").innerHTML = n;
	}
	myFunction();
</script>

resources/views/backend/includes/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{route('admin.dashboard')}}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fa fa-bug"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Chatleads Dashboard</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{{route('admin.dashboard')}}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" target="_blank" href="{{route('root')}}">
          <i class="fa fa-laptop"></i>
          <span>View Frontend</span></a>
      </li>
      <!-- Divider -->
      @hasrole('administrator')

      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        User & Role Management
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fa fa-user-circle"></i>
          <span>Users</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Manage Users:</h6>
            <a class="collapse-item" href="{{route('admin.users.create')}}"><i class="fa fa-plus"></i> Add User</a>
            <a class="collapse-item" href="{{route('admin.users.index')}}"><i class="fa fa-cogs"></i> Manage Users</a>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fa fa-user-circle"></i>
          <span>Country & Genre</span>
        </a>
        <div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Manage Country:</h6>
            <a class="collapse-item" href="{{route('admin.country.create')}}"><i class="fa fa-plus"></i> Add Country</a>
            <a class="collapse-item" href="{{route('admin.country.index')}}"><i class="fa fa-cogs"></i> Manage Country</a>
            <h6 class="collapse-header">Manage Genre:</h6>
            <a class="collapse-item" href="{{route('admin.genre.create')}}"><i class="fa fa-plus"></i> Add Genre</a>
            <a class="collapse-item" href="{{route('admin.genre.index')}}"><i class="fa fa-cogs"></i> Manage Genre</a>
          </div>
        </div>
      </li>
      @endhasrole
      <!-- Nav Item - Utilities Collapse Menu -->

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

resources/views/backend/includes/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>



            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{Auth::user()->name}}</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>