routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Backend\WelcomeController@index')->name('root');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/films','Backend\FilmController@index')->name('film.index');
Route::get('/films/{slug}','Backend\FilmController@details')->name('film.details');

Route::group(['prefix' => 'admin','as'=>'admin.','middleware' => ['role:administrator']], function () {

	Route::get('/dashboard','Backend\AdminDashboardController@adminDashboard')->name('dashboard');

	/*.............................START - User Management - START............................*/
	Route::group(['prefix' => 'users','as' => 'users.'], function () {
		Route::get('/list','Backend\UserManagementController@index')->name('index');
		Route::get('/create','Backend\UserManagementController@create')->name('create');
		Route::post('/store','Backend\UserManagementController@store')->name('store');
		Route::get('/edit/{id}','Backend\UserManagementController@edit')->name('edit');
		Route::post('/update/{id}','Backend\UserManagementController@update')->name('update');
		Route::get('/delete/{id}','Backend\UserManagementController@delete')->name('delete');
		Route::get('/ban/{id}','Backend\UserManagementController@ban')->name('ban');
		Route::get('/datatable/users','Backend\UserManagementController@userData')->name('datatables');
	});
	/*...............................END - User Management - END..............................*/

	/*.............................START - Country Management - START............................*/
	Route::group(['prefix' => 'country','as' => 'country.'], function () {
		Route::get('/list','Backend\CountryController@index')->name('index');
		Route::get('/create','Backend\CountryController@create')->name('create');
		Route::post('/store','Backend\CountryController@store')->name('store');
		Route::get('/edit/{id}','Backend\CountryController@edit')->name('edit');
		Route::post('/update/{id}','Backend\CountryController@update')->name('update');
		Route::get('/delete/{id}','Backend\CountryController@delete')->name('delete');
		Route::get('/datatable/countries','Backend\CountryController@countryData')->name('datatables');
	});
	/*...............................END - Country Management - END..............................*/

	/*.............................START - Genre Management - START............................*/
	Route::group(['prefix' => 'genre','as' => 'genre.'], function () {
		Route::get('/list','Backend\GenreController@index')->name('index');
		Route::get('/create','Backend\GenreController@create')->name('create');
		Route::post('/store','Backend\GenreController@store')->name('store');
		Route::get('/edit/{id}','Backend\GenreController@edit')->name('edit');
		Route::post('/update/{id}','Backend\GenreController@update')->name('update');
		Route::get('/delete/{id}','Backend\GenreController@delete')->name('delete');
		Route::get('/datatable/genres','Backend\GenreController@genreData')->name('datatables');
	});
	/*...............................END - Genre Management - END..............................*/
});
Route::group(['middleware' => ['role:administrator']], function () {
	/*.............................START - Genre Management - START............................*/
	Route::group(['prefix' => 'film','as' => 'film.'], function () {
		Route::get('/create','Backend\FilmController@create')->name('create');
	});
	/*...............................END - Genre Management - END..............................*/
});

app/Http/Controllers/Backend/AdminDashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminDashboardController extends Controller
{
    public function adminDashboard()
    {
    	return view('backend.dashboard.dashboard');
    }

    public function register()
    {
    	return view('backend.auth.register');
    }

    
}

app/Http/Controllers/Backend/CountryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use Illuminate\Http\Request;
use App\Country;

class CountryController extends Controller
{
    public function index()
    {
        return view('backend.country.index');
    }

    public function create()
    {
    	return view('backend.country.create');
    }

    public function store(Request $request)
    {
        $country = new Country();
        $country->name = $request->name;
        $country->code = $request->code;
        $country->save();
        return redirect()->route('admin.country.index');
    }

    public function edit($id)
    {
        $country = Country::find($id);
        return view('backend.country.edit',compact('country'));
    }

    public function update(Request $request,$id)
    {
        $country = Country::find($id);
        $country->name = $request->name;
        $country->code = $request->code;
        $country->update();
        return redirect()->route('admin.country.index');
    }

    public function delete($id)
    {  
        $country = Country::find($id);
        $country->delete();
        return redirect()->route('admin.country.index');
    }


    protected function countryData(Request $request)
    {
        $countries = Country::get();
        $datatables = Datatables::of($countries);

        return $datatables
            ->addColumn('action', function ($country) {
                return '<a href="edit/'.$country->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$country->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>';
            })
            ->editColumn('id',function($country){
                return '<b>'.$country->id.'.</b>';
            })
            ->editColumn('name',function($country){
                return $country->name;
            })
            ->rawColumns(['id','action'])
            ->make(true);
    }
}

app/Http/Controllers/Backend/FilmController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Country;
use App\Genre;
use App\Film;
use App\Comment;
use Auth;

class FilmController extends Controller
{
    public function index()
    {
        return view('frontend.film.index');
    }

    public function create()
    {
        $countries = Country::get();
        $genres = Genre::get();
        return view('frontend.film.create',compact('countries','genres'));
    }

    public function details($slug)
    {
        $film = Film::select('films.*','countries.name as country')
            ->where('films.slug',$slug)
            ->join('countries','countries.id','=','films.country_id')
            ->first();
        $genres = Genre::whereIn('id',json_decode($film->genre_id))->get();
        $film->getFirstMedia('FilmImage');
        if( count($film->media))
        $film->imgSrc = '/storage/' . $film->media[0]->id . '/' . $film->media[0]->file_name;
        $comments = Comment::where('film_id',$film->id)->get();
        if(Auth::check()) $isLoggedIn = 'true';
        else $isLoggedIn = 'false';
        return view('frontend.film.details',compact('film','comments','genres','isLoggedIn'));
    }
}

app/Http/Controllers/Backend/GenreController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use Illuminate\Http\Request;
use App\Genre;

class GenreController extends Controller
{
    public function index()
    {
        return view('backend.genre.index');
    }

    public function create()
    {
    	return view('backend.genre.create');
    }

    public function store(Request $request)
    {
        $genre = new Genre();
        $genre->name = $request->name;
        $genre->description = $request->description;
        $genre->save();
        return redirect()->route('admin.genre.index');
    }

    public function edit($id)
    {
        $genre = Genre::find($id);
        return view('backend.genre.edit',compact('genre'));
    }

    public function update(Request $request,$id)
    {
        $genre = Genre::find($id);
        $genre->name = $request->name;
        $genre->description = $request->description;
        $genre->update();
        return redirect()->route('admin.genre.index');
    }

    public function delete($id)
    {  
        $genre = Genre::find($id);
        $genre->delete();
        return redirect()->route('admin.genre.index');
    }


    protected function genreData(Request $request)
    {
        $genres = Genre::get();
        $datatables = Datatables::of($genres);

        return $datatables
            ->addColumn('action', function ($genre) {
                return '<a href="edit/'.$genre->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$genre->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>';
            })
            ->editColumn('id',function($genre){
                return '<b>'.$genre->id.'.</b>';
            })
            ->editColumn('name',function($genre){
                return $genre->name;
            })
            ->rawColumns(['id','action'])
            ->make(true);
    }
}

app/Http/Controllers/Backend/UserManagementController.php
<?php

namespace App\Http\Controllers\Backend;

use DB;
use Auth;
use App\User;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;

class UserManagementController extends Controller
{
	public function index()
    {
        return view('backend.user-management.index');
    }

    public function create()
    {
        $roles = Role::get();
    	return view('backend.user-management.create',compact('roles'));
    }

    public function store(StoreUserRequest $request)
    {
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();
        $user->assignRole($request->roles);
        return redirect()->route('admin.users.index');
    }

    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::get();
        $existingRoles = array();
        foreach ($user->roles as $role)   array_push($existingRoles, $role->name);
        return view('backend.user-management.edit',compact('user','roles','existingRoles'));
    }

    public function update(UpdateUserRequest $request,$id)
    {
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->update();
        $user->syncRoles($request->roles);
        return redirect()->route('admin.users.index');
    }

    public function delete($id)
    {  
        $user = User::find($id);
        $user->deleted_by = Auth::user()->id;
        $user->update();
        $user->delete();
        return redirect()->route('admin.users.index');
    }

    public function ban($id)
    {
        $user = User::find($id);
        $user->is_banned = !$user->is_banned;
        $user->update();
        return redirect()->route('admin.users.index');
    }

    protected function userData(Request $request)
    {
        $users = User::get();
        $datatables = Datatables::of($users);

        return $datatables
            ->addColumn('action', function ($user) {
                if($user->is_banned)
                    return '<a href="edit/'.$user->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$user->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>' . ' <a href="ban/'.$user->id.'" class="btn btn-xs btn-success" onclick="return confirm(\'Are you sure?\')"><i class="fa fa-ban"></i> Unban</a>';
                return '<a href="edit/'.$user->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>' . ' <a href="delete/'.$user->id.'" class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure?\')"><i class="glyphicon glyphicon-delete"></i> Delete</a>' . ' <a href="ban/'.$user->id.'" class="btn btn-xs btn-warning" onclick="return confirm(\'Are you sure?\')"><i class="fa fa-ban"></i> Ban</a>';
            })
            ->editColumn('id',function($user){
                return '<b>'.$user->id.'.</b>';
            })
            ->editColumn('name',function($user){
                return $user->name;
            })
            ->setRowClass(function ($user) {
                return $user->is_banned == 0 ? 'alert-success' : 'alert-danger';
            })
            ->editColumn('created_at', function ($user) {
                return $user->created_at->format('d-M-Y');
            })
            ->rawColumns(['id','action'])
            ->make(true);
    }
}

app/Http/Controllers/Backend/WelcomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {
        return view('welcome');
    }
}

resources/views/backend/user-management/create.blade.php
@extends('backend.master')

@section('title')
	Create User
@endsection

@section('mainContent')

    <div class="container">
    <h3 class="text-center text-primary"> Create User</h3>

            <h4 class="text-center text-success">{{Session::get('message')}}</h4>     
            <form class='form-horizontal' method="POST" action="{{ route('admin.users.store') }}" enctype="multipart/form-data">
            	@csrf
	          	<div class="form-group">
			      <label class="control-label col-sm-2" for="name">Name:</label>
			      <div class="col-sm-10">
			        <input type="text" class="form-control" id="name" placeholder="Enter Name" name="name" autofocus required>
					@error('name')
						<span role="alert" strong style="color:red">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				  </div>
			    </div>
			    <div class="form-group">
			      <label class="control-label col-sm-2" for="email">Email:</label>
			      <div class="col-sm-10">
			        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
					@error('email')
						<span role="alert" strong style="color:red">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				  </div>
			    </div>
			    <div class="form-group">
			      <label class="control-label col-sm-2" for="pwd">Password:</label>
			      <div class="col-sm-10">
			        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="password">
					@error('password')
						<span role="alert" strong style="color:red">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				  </div>
			    </div>

			    <div class="form-group">
			      <label class="control-label col-sm-2" for="pwd">Roles:</label>
			      @foreach($roles as $role)  
			        <input type="checkbox" name="roles[]" value="{{$role->name}}" {{$role->name == 'user' ? 'checked' : ''}}/> {!! $role->name !!} 
			      @endforeach
			    </div>


		    	<div class="form-group">
		            <div class="col-sm-offset-2 col-sm-10">
		                <a class="btn btn-danger" href="{{route('admin.users.index')}}">Cancel</a>
		                <button type="submit" class="btn btn-success" name="sub">Create User</button>
		            </div>
		         </div>
        </form>
</div>
@endsection

resources/views/backend/user-management/edit.blade.php
@extends('backend.master')

@section('title')
	Edit User
@endsection

@section('mainContent')

    <div class="container">
    <h3 class="text-center text-primary"> Edit User</h3>
    
            <h4 class="text-center text-success">{{Session::get('message')}}</h4>     
            <form class='form-horizontal' method="POST" action="{{ route('admin.users.update',['id' => $user->id]) }}" enctype="multipart/form-data">
            	@csrf
				<div class="form-group">
			      <label class="control-label col-sm-2" for="name">Last Name:</label>
			      <div class="col-sm-10">
			        <input type="text"  value="{{$user->name}}" class="form-control" id="name" placeholder="Enter Name" name="name" required>
					@error('name')
						<span role="alert" strong style="color:red">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				  </div>
			    </div>
			    <div class="form-group">
			      <label class="control-label col-sm-2" for="email">Email:</label>
			      <div class="col-sm-10">
			        <input type="email" value="{{$user->email}}" class="form-control" id="email" placeholder="Enter email" name="email">
					@error('email')
						<span role="alert" strong style="color:red">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				  </div>
			    </div>
			    <div class="form-group">
			      <label class="control-label col-sm-2" for="pwd">Roles:</label>
			      @foreach($roles as $role)  
			        <input type="checkbox" name="roles[]" value="{{$role->name}}" {{ in_array($role->name, $existingRoles) ? 'checked' : ''}}/> {!! $role->name !!} 
			      @endforeach
			    </div>
		    	<div class="form-group">
		    		
		            <div class="col-sm-offset-2 col-sm-10">
		            	<a class="btn btn-danger" href="{{route('admin.users.index')}}">Cancel</a>
		                <button type="submit" class="btn btn-success" name="sub">Update User</button>
		            </div>
		         </div>
        </form>
</div>
@endsection

resources/views/backend/user-management/index.blade.php
@extends('backend.master')

@section('title')
    User List
@endsection

@section('mainContent')
<!-- 
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">-->
                <!-- <h4 class="text-center text-success">{{Session::get('message')}}</h4>      -->
                <div class="table-responsive">
                    <table class="table table-bordered" id="category-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Member Since</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
      <!--       </div>
        </div>
    </div>
</div> -->
@stop
@push('scripts')
<script>
$(function() {
    // var i=1;
    $('#category-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('admin.users.datatables') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'created_at', name: 'created_at' },
            {data: 'action', name: 'action', orderable: false, searchable: false},
            // { data: 'updated_at', name: 'updated_at' }
        ]
    });
});
</script>
@endpush